/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author almc
 */
public class Interfaz extends javax.swing.JFrame {
    private ListaProductos lista = new ListaProductos();
    private ArrayList<String> nombres;
    
    public Interfaz() {
        initComponents();
        nombres = lista.nombres();
        for(String s:nombres) {
            jcb.addItem(s);
        }
        lblTotal.setText("0.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jcb = new javax.swing.JComboBox<>();
        lblID = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        spin = new javax.swing.JSpinner(new SpinnerNumberModel(1,1,500,1));
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPV");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(300);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 660, 230));

        jcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un producto" }));
        jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActionPerformed(evt);
            }
        });
        getContentPane().add(jcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 460, -1));

        lblID.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 50));

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setText("TOTAL :");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, 50));

        lblTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        panel.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 150, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setText("€");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 20, 50));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 660, 70));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 10, 310));
        getContentPane().add(spin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 90, -1));

        btnAdd.setText("AGREGAR PRODUCTO");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 210, 50));

        btnDelete.setText("ELIMINAR PRODUCTO");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 230, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionPerformed
        if(!jcb.getModel().getSelectedItem().equals("Seleccione un producto")) {
            String producto = (String)jcb.getModel().getSelectedItem();
            String id = Integer.toString(Consultas.consultaID(producto));
            lblID.setText(id);
        }else{
            lblID.setText("");
        }
    }//GEN-LAST:event_jcbActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Consultas.cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(!jcb.getModel().getSelectedItem().equals("Seleccione un producto")) {
            String nombre = (String)jcb.getModel().getSelectedItem();
            float precio = Consultas.consultaPrecio(nombre);
            int cantidad = (int) spin.getValue();
            Producto producto = new Producto(Integer.parseInt(lblID.getText()),nombre,precio);
            
            DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
            Object[] fila = new Object[4];
            fila[0] = producto.getId();
            fila[1] = producto.getNombre();
            fila[2] = cantidad;
            fila[3] = producto.getPrecio()*cantidad;
            modelo.addRow(fila);
            float preciototal = 0;
            for (int i=0; i<modelo.getRowCount(); i++) {
                preciototal += (float) modelo.getValueAt(i, 3);
            }
            preciototal = (float) (preciototal*1.21);
            float round =(float) ((float) Math.round(preciototal * 100.0)/100.0);
            lblTotal.setText(Float.toString(round));
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel modelo = (DefaultTableModel)tabla.getModel();
        int r = tabla.getSelectedRow();
        if(r<0) {
            JOptionPane.showMessageDialog(this,"Debe seleccionar un registro");
        }else{
            modelo.removeRow(r);
        }
        float preciototal = 0;
        for (int i=0; i<modelo.getRowCount(); i++) {
            preciototal += (float) modelo.getValueAt(i, 3);
        }
        preciototal = (float) (preciototal*1.21);
        float round =(float) ((float) Math.round(preciototal * 100.0)/100.0);
        lblTotal.setText(Float.toString(round));
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panel;
    private javax.swing.JSpinner spin;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
